### ISSUE TITLE
Deliverable #4

### ISSUE THREAD

**Issue by AhadKhan98** [Berea-CS-Courses/capstone-project-AhadKhan98#10]
__This document contains the midterm proof of concept, along with supporting documentation.__

__I would like feedback on ...__ 
- Whether the proof of concept is viable
- Feedback on all different sections in my document

**Comment by jazzij** [comment]
The server connection demo is a good start, but not quite to where we'd hoped for the proof of concept. Since your core feature to allow people to send messages back and forth in a chat room, it would have been great to see a way for users to provide some input text, route it through the server, and show its receipt by some other user

**Comment by AhadKhan98** [comment]
@jazzij I understand. I have added a real-time chat functionality to the project. The users can now chat in real-time using sockets and, the backend and the frontend still have the functionality to communicate with each other.

**Comment by jazzij** [comment]
The chat demo looked great!
